### ISSUE TITLE
[CCK.Debugger] Props trigger button changes when pinned

### ISSUE THREAD

**Issue by NotAKidOnSteam** [kafeijao/Kafe_CVR_Mods#8] opened 2022-10-29 07:21 UTC
;-;

https://user-images.githubusercontent.com/37721153/198819235-b8f09e23-6c47-4340-99ca-1b555ab81919.mp4

such a minuscule issue cannot be excused 😠 😠 😳 😠

**Comment by kafeijao** [comment] 2022-10-29 14:42
Oof the unity UI is a nightmare, had so many silly issues. If you have any idea how to fix it I'll welcome it :)

**Comment by kafeijao** [comment] 2022-10-31 13:49
Might be fixed in https://github.com/kafeijao/Kafe_CVR_Mods/commit/3fd688f44bdfe7a82483143d9b0eadcb28b80a94
I couldn't reproduce it tho, I also had some weird jitter when pinning, but not that specific one. My jitter is gone now so... 🤞

**Comment by kafeijao** [comment] 2022-11-09 14:57
Going to close because I feel like this was solved. Re-open otherwise.

**Closed by kafeijao** 2022-11-09 14:57 UTC
Labels: help wanted, CCK.Debugger
